### ISSUE TITLE
Copy & Pasting Into Simulator

### ISSUE THREAD

**Issue by baileyparker** [skilldrick/easy6502#10]
Currently, when you copy and paste code overtop of existing code into the simulator, it does not recognize that the code has changed and leaves the assemble button greyed out.

I imagine this is something to do with the event you are using to detect changes in the textfield. Certain events aren't thrown for pasting.

Similarly, if you delete a character, the assemble button still remains grey. Again, this is likely because the event used to watch for changes in the code does not fire when non character-producing keys are pressed.

I can dig into the source and submit a PR if need be.

Thanks,
Bailey

**Comment by BigEd** [comment]
A minimal patch for this would be appreciated!  We should test on Chrome, Firefox and Safari on Linux, Windows and OSX, if possible, so please let me know which platforms you can cover.

**Comment by baileyparker** [comment]
This is a really minimal patch. I can confirm Firefox and Safari (can confirm more later), but testing all of these and different OS's is really unnecessary. This behavior is [well documented](https://developer.mozilla.org/en-US/docs/Web/Events/keypress) (the `keypress` event that you use to listen for changes in the code editor only fires when an actual character is produced, so this means it won't fire for pasting or delete operations like backspace). The solution is to use the input [event](https://developer.mozilla.org/en-US/docs/Web/Events/input), which is supported by all modern browsers (Chrome, Safari, FF, and Opera supported it from the start, IE > 9, but 6-8 are so low use it doesn't really matter). The input event fires on any update to an input or textarea that would modify its `.value`.

**Comment by BigEd** [comment]
Great - thanks!
