### ISSUE TITLE
Warning if Unable to Branch

### ISSUE THREAD

**Issue by baileyparker** [skilldrick/easy6502#11]
Currently if you try to branch to an address (that I presume is more than 128 bytes away, although I'm not positive on this exact number), the simulator will just jump to some high memory address and everything will eventually fail.

On a real 6502, I realize that this is expected behavior, however since this is a simulator, I think it would be beneficial to display a warning message in the log indicating that a too distant branch was attempted.

I can (as before) submit a PR after I have a chance to comb through the responsible code if you agree that this would be a good feature to add.

**Comment by BigEd** [comment]
You're right: an out of range branch is incorrectly handled.  This should fail at assembly time.

**Comment by BigEd** [comment]
If you could make a small patch around
https://github.com/skilldrick/easy6502/blob/gh-pages/simulator/assembler.js#L2089
that would be great. I think we should have a
var distance;
and once the distance is computed, compare it against the maximum allowed distance (one signed byte) before using it.
