### ISSUE TITLE
Link is dead at 'Learn more about the registers and flags here.'

### ISSUE THREAD

**Issue by anthonydotmoe** [skilldrick/easy6502#23]
It used to go to to [http://www.obelisk.demon.co.uk/6502/registers.html](http://www.obelisk.demon.co.uk/6502/registers.html). But it would appear the link is dead.

**Comment by BigEd** [comment]
Thanks for the report - I think I've fixed it.

**Comment by anthonydotmoe** [comment]
Alright! Link Works! (Good resource too!)
