### ISSUE TITLE
Accumulator addressed instructions are broken

### ISSUE THREAD

**Issue by pawwkm** [skilldrick/easy6502#24]
The following code 

``` assembly
asl a
lsr a
rol a
ror a
```

should result in **0A 4A 2A 6A**, but instead it is assembled as **0e ff ff 4e ff ff 2e ff ff 6e ff ff**

**Comment by BigEd** [comment]
Looks like easy6502 follows the other convention, where no operand means accumumulator mode:

```
asl 
lsr 
rol 
ror 
```

As it happens, the disassembler puts the A back in, which isn't ideal...

**Comment by pawwkm** [comment]
Ah, my bad. I forgot that no operator means accumulator addressing mode :)

**Comment by BigEd** [comment]
I'll close this - hope that's OK
