### ISSUE TITLE
Significant typo in index.markdown

### ISSUE THREAD

**Issue by RGrun** [skilldrick/easy6502#26]
As you describe the snake game, you have this paragraph:

"The hex value $03 is represented in binary as 00000111. The AND opcode performs a bitwise AND of the argument with the accumulator. For example, if the accumulator contains the binary value 01010101, then the result of AND with 00000111 will be 00000101."

The binary value of $03 is 00000011. This could be very confusing to people.

**Comment by BigEd** [comment]
Good catch - thanks! Corrected/Adjusted.
