### ISSUE TITLE
low contrast text can be hard to read

### ISSUE THREAD

**Issue by danbri** [skilldrick/easy6502#28]
can you make the text higher contrast please?

**Comment by BigEd** [comment]
I think we already changed to a hard black two years ago - can you somehow share the CSS that's  applied in your case?
See
https://github.com/skilldrick/easy6502/commit/d9116b900f563e7210ad2035ec389612ecc27d95

**Comment by mirao** [comment]
I can confirm it's hard to read the text. This is how it look in Chrome 107 on Ubuntu 22.04
![image](https://user-images.githubusercontent.com/12584138/202784639-a635527d-6ca1-4ea8-b3c7-2c653085f091.png)

**Comment by BigEd** [comment]
Was difficult for me to read too.  I couldn't find a way to get the Lato font to come out at a decent weight, so I removed it - the fallback Helvetica Neue is pretty similar anyway.

Hope this is OK by @skilldrick

**Comment by skilldrick** [comment]
@BigEd thanks! I noticed that there was an issue with the width of the header so I fixed that in a [separate commit](https://github.com/skilldrick/easy6502/commit/e7b16e61054757cba360742b62be40d96dc6d7d8).
<img width="410" alt="image" src="https://user-images.githubusercontent.com/153525/203130404-7875b4d8-ba28-431e-b3ca-6de20752cafa.png">
