### ISSUE TITLE
This is more of a question than an issue.

### ISSUE THREAD

**Issue by Mr-Tibbs** [skilldrick/easy6502#32]
Firstly, I think this assembler is amazing and I love that I can mess with an app that is actually fun in my spare time. Now, I have been trying to move a pixel on the screen up, down, left, and right. Sounds easy enough, but the amount of bytes that the addresses can store is only so much and I can only move the pixel on the top section of the screen, Obviously! XD I know that this was the case back then with the 6502, but I was wondering how I could add to my atrocious code to make the pixel move all over the screen I just don't think that I am getting how all the addressing modes work, actually a bit of clarification on how indirect and indirect indexed addressing modes work would be greatly appreciated in the tutorials because they are kind of confusing the way they are worded, the rest is great though, good work.

`;$01 is color of pixel
;$02 is empty for color black 
;$03 is color for up and down's X increment 
;$04 is counter for next set of pixels 
LDA #$01
STA $01 
 JMP input
 
reset: 
LDA $03 
DEC $03 
CMP #$00 
 BNE reset 
DEC $ff 
CMP #$00 
 BEQ input
 
input: 
LDA $ff 
CMP #$77 ;UP 
 BEQ up 
LDA $ff 
CMP #$61 ;LEFT 
 BEQ left 
LDA $ff 
CMP #$73 ;DOWN 
 BEQ down 
LDA $ff 
CMP #$64 ;RIGHT 
 BEQ right 
  JMP input
 
up: 
LDA $02 
STA $01ff, X 
DEX 
LDA $03 
ADC #$01 
STA $03 
CMP #$20 

BNE up 
LDA $01 
STA $01ff, X 
 JMP reset 

left:
LDA $02 
STA $01ff, X 
DEX 
LDA $02 
STA $01ff, X 
LDA $01 
STA $01ff, X 
 JMP reset
 
down: 
LDA $02 
STA $01ff, X 
INX 
LDA $03 
ADC #$01 
STA $03 
CMP #$20 
 BNE down 

LDA $01 
STA $01ff, X 
 JMP reset 

right:
LDA $02 
STA $01ff, X 
INX 
LDA $02 
STA $01ff, X 
LDA $01 
STA $01ff, X 
 JMP reset`

**Comment by BigEd** [comment]
Can I suggest you have a careful read through the final program, the Snake game? It should answer both the question of how to do things and the question about the addressing modes.
