### ISSUE TITLE
Example overwrites program memory

### ISSUE THREAD

**Issue by inindev** [skilldrick/easy6502#37]
In the Indexed indirect example you overwrite program memory with ```STY $0605```.  Also, you setup $01 $02 with #$0605 but then do not use it.  I think the example needs a tweak.

```
###Indexed indirect: ($c0,X)###

This one’s kinda weird. It’s like a cross between zero page,X and indirect. Basically, you take the zero page address, add the value of the X register to it, then use that to look up a two-byte address. For example:

LDX #$01
LDA #$05
STA $01
LDA #$06
STA $02
LDY #$0a
STY $0605
LDA ($00,X)

https://skilldrick.github.io/easy6502/#addressing
```

Also, github apparently changed their markdown engine and your headers now need a space between the ### and the text to render properly.

```###Indexed indirect: ($c0,X)###```
###Indexed indirect: ($c0,X)###

```### Indexed indirect: ($c0,X) ###```

**Comment by BigEd** [comment]
Thanks - I've made minimal tweaks to address both points.
