### ISSUE TITLE
Open source licence

### ISSUE THREAD

**Issue by isedwards** [skilldrick/easy6502#46]
I'd like to adapt this to work on physical hardware.

Can you clarify which open source/creative commons licence(s) you'd like derivatives to be released under?

**Comment by BigEd** [comment]
It's a GPL project as it stands:
https://github.com/skilldrick/easy6502/blob/gh-pages/simulator/assembler.js#L8

Is that OK for you?  Otherwise you'll need to hear from @skilldrick 
Edit: oh, and also Stian, the upstream author.

**Comment by isedwards** [comment]
Thank you @BigEd

I agree `assembler.js` is GPL 3
(because it is adapted from
http://6502asm.com/assembler.js.php)

The included `es5-shim.js` has an MIT license.

I'm really interested in Nick's tutorial text in `index.markdown` (and the assembly code within it).

@skilldrick perhaps the tutorial itself is most suited to a creative commons license?

I'm intending to run this on a real processor, so the JavaScript code isn't really of interest to me.

**Comment by skilldrick** [comment]
@isedwards yes, I'm fine with classing this as CC BY. I'd happily accept a pull request to make that official.

**Comment by isedwards** [comment]
Thank you @skilldrick, I'll send a PR in the next couple of days.
Also, thank you for writting this tutorial in the first place, a lot of people have enjoyed it over the years!
