### ISSUE TITLE
Reset doesn't completely reset?  (program behaves differently first-run vs reset-run)

### ISSUE THREAD

**Issue by cellularmitosis** [skilldrick/easy6502#50]
First, thanks so much for making Easy 6502! 🤩

I noticed something funny when trying to draw a single-pixel border around the edge of the "screen": my program has different behavior after a "Reset".

The first time I run the code, it works correctly:

![Screen Shot 2021-06-06 at 1 03 23 AM](https://user-images.githubusercontent.com/223396/120914314-0b628500-c663-11eb-8128-9313e63fd1e9.png)

But if I then click "reset" and "run", my program behaves differently: it gets stuck in an infinite loop while trying to draw the right-hand border:

https://user-images.githubusercontent.com/223396/120914380-9b083380-c663-11eb-821a-089553e3b3b9.mp4

If I then make a trivial change (e.g. add an extra space), I can click "Assemble" and "Run" and the program works again.

Is this a bug?  I would have expected that "Reset" would perform a full reset, but it appears there is some leftover state which is causing my program to behave differently the second time around.

**Comment by cellularmitosis** [comment]
Oops, forgot to paste the program:

```
; program: draw a one-pixel-thick border around the screen.

 LDX #5       ; green.

; draw the top row of pixels
 LDY #0       ; pixel offset.
 TXA
 STA $0200,Y  ; draw.
loop1:
 INY
 STA $0200,Y  ; draw.
 CPY #31      ; if Y != 31, loop.
 CLC
 BNE loop1

; draw the right column of pixels
 LDA #$3F     ; store 0x023F at 0x0000
 STA $0
 LDA #$02
 STA $1

 LDY #0       ; pixel offset.
 TXA
 STA ($0),Y   ; draw.
loop2:
 TYA
 ADC #$20     ; advance by 0x20 (one row).
 TAY
 TXA
 STA ($0),Y   ; draw.
 CPY #$E0     ; if Y != 0xE0, loop.
 CLC
 BNE loop2

 LDA $1
 ADC #1       ; increment the pixel page.
 STA $1
 CMP #6       ; stop when you reach page 6.
 CLC
 BNE loop2
 
; draw the bottom row of pixels
 LDY #31
 TXA
 STA $05E0,Y
loop3:
 DEY
 STA $05E0,Y
 CPY #0
 CLC
 BNE loop3

; draw the left column of pixels
 LDA #$00     ; store 0x0200 at 0x0000
 STA $0
 LDA #$02
 STA $1

 LDY #0       ; pixel offset.
 TXA
 STA ($0),Y   ; draw.
loop4:
 TYA
 ADC #$20     ; advance by 0x20 (one row).
 TAY
 TXA
 STA ($0),Y   ; draw.
 CPY #$00     ; if Y != 0x00, loop.
 CLC
 BNE loop4
    
 LDA $1
 ADC #1       ; increment the pixel page.
 STA $1
 CMP #6       ; stop when you reach page 6.
 CLC
 BNE loop4
 
 BRK          ; done.
```

**Comment by BigEd** [comment]
There is a bug, but (I believe) it's in your code!  If you use the Disassemble button on your code as-pasted, and then use it again after the code has been run, we see that a byte of the program has been overwritten:
```
$061b    8a        TXA 
$061c    91 00     STA ($00),Y
$061e    98        TYA 
$061f    69 20     ADC #$20
$0621    a8        TAY 
$0622    8a        TXA 
```
after:
```
$061b    8a        TXA 
$061c    91 00     STA ($00),Y
$061e    98        TYA 
$061f    05 20     ORA $20
$0621    a8        TAY 
$0622    8a        TXA 

```

**Comment by pepasibble** [comment]
Ah thank you so much for the insight!  Looks like I have accidentally discovered self-modifying code 😅

![5ejnu2](https://user-images.githubusercontent.com/78579108/123475914-b068e180-d5c1-11eb-9228-9a547ccef935.jpg)

**Comment by BigEd** [comment]
Hope it's OK to close.

**Comment by pepasibble** [comment]
Yes!  thank you.  (this is my work account 😃)
