### ISSUE TITLE
Easy Way to Mirror?

### ISSUE THREAD

**Issue by phf** [skilldrick/easy6502#8]
I hope this is not too trivial to ask. I would like to use Easy6502 for a course I am teaching, but I'd like to make sure that it stays accessible for the life of the assignments that I'll give. So I'd prefer to mirror the entire working Easy6502 site in a way to insulates me from changes. Can that be done in a straightforward way? Is it enough to just grab everything from the gh-pages that host the tutorial and slap it on my own server? Or is everything heavily tied into github specific things?

**Comment by BigEd** [comment]
I think you will be OK if you just grab a copy.  Or, take a fork and use your own gh-pages,

**Comment by BigEd** [comment]
Hope that worked for you.
